title: Tokyo Adachi Roshukai UK
description: The Tokyo Adachi Roshukai is a group dedicated to the study of Muso Jikiden Eishin Ryu Iai in the UK.
font: "https://fonts.googleapis.com/css?family=Source+Code+Pro|Roboto:400,700"

collections:
  dojos:
    output: true
  honourable_mentions:
    output: true